# Generated by Django 5.1.6 on 2025-02-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsCensusBureauCache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address_string", models.CharField(db_index=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=dict, help_text="Data retrieved from US Census API")),
                (
                    "matched_address",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="address.address"),
                ),
            ],
        ),
    ]
