# Generated by Django 5.1.6 on 2025-02-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0003_auto_20200628_1920"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
